Infrastructure/Infrastructure.Pay/Models/PaymentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pay.Models
{
    public class PaymentModel
    {
        public int Amount { get;  set; }
        public Guid UserId{ get;  set; }
        public string Mobile { get;  set; }
        public string NationalCode { get;  set; }
        public bool IsWeb { get;  set; }
        public string Name { get;  set; }
        public string Message { get; set; }
    }
}

Infrastructure/Infrastructure.Pay/Controllers/PayController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Pay.Models;
using Core.Contracts;
using Utility.Tools.General;
using Core.Entities.GlobalSettings;
using Core.Entities;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks;
using Core.Entities.Dto;
using Zarinpal;
using Enums;

namespace Infrastructure.Pay.Controllers
{

    public class PayController : Controller
    {
        //http://localhost:5555/?param=y7N2S5e67781l3l3o1L920J!m0f0B015S!d6a772K4z7K1J8w802N1/////////////////////////////////////////////////

        private readonly IUnitOfWork unit;
        private readonly IConfiguration configuration;

        public string Link = "";
        public string Merchant = "";

        public PayController(IUnitOfWork unit, IConfiguration configuration)
        {
            this.unit = unit;
            this.configuration = configuration;
        }

        [HttpPost]
        public async Task<ApiResult> StartPay([FromBody]PaymentModel model)
        {
            //return new ApiResult { Message = Agent.ToJson(model)};
            var result = new ApiResult { Status = false, Message = Messages.GatewayError };

            configuration.GetSection<PaymentData>();
            //Merchant = unit.Users.GetMerchant(model.UserId);
            //if (Merchant == null)
                Merchant = PaymentData.Account;



            var Authority = await CreateLinkAsync(model);
            
            if (Authority != null && Authority != "")
            {
                if (!unit.Transaction.IsAuthorityExist(Authority))
                {
                    unit.Transaction.Add(new Transaction
                    {
                        Amount = model.Amount,
                        Authority = Authority,
                        CreatedAt = DateTime.Now.ToUnix(),
                        UserId = model.UserId,
                        TransactionCategoryId = TransactionType.Gateway.ToInt()
                    });
                    unit.Complete();
                    result.Status = true;
                    result.Response = Link;
                }
                else
                    result.Message = Messages.AuthorityExist;
            }



            return result;

        }
        public async Task<IActionResult> MobileVerify(string Status, string Authority)
        {
            return await VerifyProcess(Status, Authority);
        }
        public async Task<IActionResult> WebVerify(string Status, string Authority)
        {
            return await VerifyProcess(Status, Authority);
        }
        public IActionResult BadPrice()
        {
            return View();
        }


        [NonAction]
        private async Task<string> CreateLinkAsync(PaymentModel model)
        {
            
            Payment pay = new Payment(Merchant, model.Amount);

            var result = !model.IsWeb ? await pay.PaymentRequest(model.Mobile, PaymentData.MobileAddress, PaymentData.Email, model.Mobile)
                : await pay.PaymentRequest(model.Mobile, PaymentData.WebAddress, PaymentData.Email, model.Mobile);

            string Authority = null;
            if (result != null)
            {
                Link = result.Link;
                Authority = result.Authority;
            }
            else
                ResetModel(model);
            return Authority;
        }
        [NonAction]
        private async Task<IActionResult> VerifyProcess(string Status, string Authority)
        {
            configuration.GetSection<PaymentData>();
            PaymentModel model = new PaymentModel();
            if (Status != null && Authority != null)
            {
                Transaction transaction = unit.Transaction.GetByAuthority(Authority);
                if (transaction == null)
                    model.Message = "محصول وجود ندارد";
                else if (transaction.IsSuccessful)
                    model.Message = "این کد پیگیری قبلا ذخیره شده است";
                else
                {
                    var pay = new Payment(PaymentData.Account, transaction.Amount);
                    var result = await pay.Verification(Authority);
                    if (result != null)
                    {
                        transaction.RefId = result.RefId.ToString();
                        var state = result.Status;
                        if (Status == "OK")
                        {
                            model.Amount = transaction.Amount;
                            transaction.IsSuccessful = true;
                            model.Message = "پرداخت شما با موفقیت انجام شد";
                        }
                        else if (Status.ToString() == "NOK")
                        {
                            transaction.IsSuccessful = false;
                            model.Message = GetErrorMessage(state);
                            transaction.Description = model.Message;
                        }
                        unit.Complete();
                    }
                    else
                        ResetModel(model);
                }
            }
            return View(model);
        }
        [NonAction]
        private void ResetModel(PaymentModel model)
        {
            model.Message = "پارامترها غلط است";
        }
        [NonAction]
        internal static string GetErrorMessage(int state)
        {
            switch (state)
            {
                case -1:
                    return "اطلاعات ارسال شده ناقص است";
                case -2:
                    return "IP و يا مرچنت كد پذيرنده صحيح نيست";
                case -3:
                    return "با توجه به محدوديت هاي شاپرك امكان پرداخت با رقم درخواست شده ميسر نمي باشد";
                case -4:
                    return "سطح تاييد پذيرنده پايين تر از سطح نقره اي است";
                case -11:
                    return "درخواست مورد نظر يافت نشد";
                case -12:
                    return "امكان ويرايش درخواست ميسر نمي باشد";
                case -21:
                    return " نوع عمليات مالي براي اين تراكنش يافت نشد";
                case -22:
                    return "تراكنش نا موفق مي باشد";
                case -33:
                    return "رقم تراكنش با رقم پرداخت شده مطابقت ندارد";
                case -34:
                    return "سقف تقسيم تراكنش از لحاظ تعداد يا رقم عبور نموده است";
                case -40:
                    return "اجازه دسترسي به متد مربوطه وجود ندارد";
                case -41:
                    return "اطلاعات ارسال شده مربوط به AdditionalData غيرمعتبر مي باشد";
                case -42:
                    return " زمان معتبر طول عمر  شناسه  پرداخت بايد بين 30دقيه تا 45روز مي باشد";
                case -54:
                    return "درخواست مورد نظر آرشيو شده است";
                case 99:
                    return "عمليات با موفقيت انجام گرديده است";
                case 100:
                    return "عمليات با موفقيت انجام گرديده است";
                case 101:
                    return "عمليات پرداخت موفق بوده وقبلا تراكنش انجام شده است";
                default:
                    return "خطای ناشناخته";
            }
        }
    }
}

Infrastructure/Infrastructure.Pay/Views/Pay/Index.cshtml
@model PaymentModel
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>درگاه پرداخت</title>
    <link href="/css/bootstrap.css" rel="stylesheet" />
    <link href="/css/bootstrap-rtl.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="row" style="margin-top: 50px;">
            <div class="col-lg-6 center-block" style="float: none;">
                <div class="panel panel-primary">
                    <div class="panel-heading">اتصال به درگاه پرداخت</div>
                    <div class="panel-body">
                        <form asp-action="Index" asp-controller="Pay" class="form-horizontal">
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <label asp-for="Amount"></label>
                                </div>
                                <div class="col-sm-12">
                                    <input asp-for="Amount" class="form-control"/>
                                </div>
                                <div class="col-sm-12 text-left">
                                    <span asp-validation-for="Amount" style="color: red"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <br />
                                    <input type="submit" value="اتصال به درگاه پرداخت" class="btn btn-success" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12" style="color: red">@ViewBag.Error</div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Infrastructure/Infrastructure.Pay/Views/Pay/MobileVerify.cshtml
@model Pay.Models.PaymentModel
<link href="/css/bootstrap.css" rel="stylesheet" />

<div class="card bg-white" style="margin:auto auto;">




    <center class="p-5 bg-danger">

        <label id="Message" class="h4 text-white">@Model.Message</label>
    </center>




    <table class="table table-bordered table-striped" style="align-content:center;margin:auto auto 32px auto;">
        
        <tr>
            <td style="width:50%; align-content:center;text-align:center;">
                <label id="lbl4" class="text-dark bg-info">میزان پرداخت</label>

            </td>
            <td style="width:50%;align-content:center;text-align:center;">
                <label id="Amount" class="text-dark bg-info">@Model.Amount</label>
            </td>

        </tr>
    </table>

    <table class="table" style="width:100%;align-content:center;">
        <tr>
            <td style="align-content:center;text-align:center;">
                <button id="back-btn" class="btn btn-success bg-info" onclick="backToKargozar()">بازگشت به موبایل</button>
            </td>
        </tr>
    </table>

</div>


<script>

    function backToKargozar() {

        @*window.location = '@PaymentData.MobileActivity';*@
        window.location = 'uniwebview://close';
        //window.location = 'intent:#Intent;action=schemas.kargozar.mekargozar.MainActivity;end';
    }
</script>



@*var loc;


    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
        loc = '@PaymentData.MobileActivity';

    } else {
        loc = "@PaymentData.SiteAddress"
        document.getElementById("back-btn").innerHTML='بازگشت به سایت';
    }*@

Infrastructure/Infrastructure.Pay/Views/Pay/StartPay.cshtml
<html>
<head>
    <link href="~/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <style>
        body {
            background-color: white;
        }

        h1 {
            color: red;
            margin-left: 150px;
        }

        .auto-style1 {
            color: #0000FF;
            text-align: right;
        }
    </style>

    <style>
        .Error {
            background-color: burlywood;
        }



        .Error {
            font-size: xx-large;
            color: #ff0000;
        }
    </style>

    <meta name="viewport" content="width=1024">

    <style>
        .btn-Hiwa {
            color: #fff;
            background-color: #28a745;
            border-color: #28a745;
            font-size: xx-large;
            font-family: 'B Yekan';
            direction: rtl;
            align-items: center;
            text-align: center;
        }

            .btn-Hiwa:hover {
                color: #fff;
                background-color: #218838;
                border-color: #1e7e34;
                font-size: xx-large;
            }

            .btn-Hiwa:focus, .btn-success.focus {
                box-shadow: 0 0 0 0.2rem rgba(40, 167, 69, 0.5);
                font-size: xx-large;
            }

            .btn-Hiwa.disabled, .btn-Hiwa:disabled {
                color: #fff;
                background-color: #28a745;
                border-color: #28a745;
                font-size: xx-large;
            }

            .btn-Hiwa:not(:disabled):not(.disabled):active, .btn-Hiwa:not(:disabled):not(.disabled).active,
            .show > .btn-Hiwa.dropdown-toggle {
                color: #fff;
                background-color: #1e7e34;
                border-color: #1c7430;
                font-size: xx-large;
            }

                .btn-Hiwa:not(:disabled):not(.disabled):active:focus, .btn-Hiwa:not(:disabled):not(.disabled).active:focus,
                .show > .btn-Hiwa.dropdown-toggle:focus {
                    box-shadow: 0 0 0 0.2rem rgba(40, 167, 69, 0.5);
                    font-size: xx-large;
                }
    </style>

    <style>
        .table-bordered {
            border: 1px solid #dee2e6;
        }

            .table-bordered th,
            .table-bordered td {
                border: 1px solid #dee2e6;
            }

            .table-bordered thead th,
            .table-bordered thead td {
                border-bottom-width: 2px;
            }
    </style>

    <style>
        .table-success,
        .table-success > th,
        .table-success > td {
            background-color: #c3e6cb;
        }

        .table-hover .table-success:hover {
            background-color: #b1dfbb;
        }

            .table-hover .table-success:hover > td,
            .table-hover .table-success:hover > th {
                background-color: #b1dfbb;
            }
    </style>

    <style>
        .table-primary,
        .table-primary > th,
        .table-primary > td {
            background-color: #b8daff;
        }

        .table-hover .table-primary:hover {
            background-color: #9fcdff;
        }

            .table-hover .table-primary:hover > td,
            .table-hover .table-primary:hover > th {
                background-color: #9fcdff;
            }
    </style>

    <style>
        div {
            width: 100%;
            margin: 0px auto;
            align-content: center;
            font-size: xx-large;
        }
    </style>
    <style>
        .main {
            color: blue;
            font-family: 'B Yekan';
        }
    </style>



    @*@media (max-width: 768px) {
        div {
        margin:0px auto;

        font-size:medium;
        }

        .btn-Hiwa{
        font-size:medium;
        }
        }*@

    <div style="margin:0px auto;">



        <table class="table" style="width:100%;align-content:center;text-align:center;">
            <tr>
                <td style="align-content:center;text-align:center">
                    <img id="Image1" style="height:80px; width:80px;align-content:center;" src="~/images/ic_logo.png" />

                </td>
            </tr>

            <tr>
                <td style="align-content:center;text-align:center;font-family:B Yekan;">
                    <p> سیستم بررسی ویزای آلمان </p>

                </td>
            </tr>

        </table>



        <table class="table" style="width:100%;align-content:center;text-align:center;">
            <tr>
                <td style="align-content:center;text-align:center;">
                    <label id="Message" class="Error" style="font-family:B Yekan;">سامانه قادر به اتصال به درگاه نیست</label>

                </td>
            </tr>
        </table>

        <br /><br />
        <table class="table" style="width:100%;align-content:center;">
            <tr>
                <td style="align-content:center;text-align:center;">
                    <button class="btn-Hiwa" onclick="backToKargozar()">بازگشت به موبایل </button>
                </td>
            </tr>
        </table>

    </div>
</body>
</html>
<script>

    function backToKargozar() {
        window.location = "intent:#Intent;action=schemas.ir.erenco.germany.PassportServicesActivity;end";
    }
</script>

Infrastructure/Infrastructure.Pay/Views/Pay/WebVerify.cshtml
@model Pay.Models.PaymentModel
<link href="/css/bootstrap.css" rel="stylesheet" />



<div class="card bg-white" style="margin:auto auto;">




    <center class="p-5 bg-danger">

        <label id="Message" class="h4 text-white">@Model.Message</label>
    </center>




    <table class="table table-bordered table-striped" style="align-content:center;margin:auto auto 32px auto;">
        @*<tr>
            <td style="align-content:center;text-align:right;width:50%;">
                <label id="lbl1" class="text-dark">کد کاربر</label>
            </td>
            <td style="align-content:center;text-align:right;">
                <label id="Name" class="text-dark">@Model.Code</label>
            </td>

        </tr>*@

        @*<tr>
            <td style="align-content:center;text-align:right;">
                <asp:Label ID="lbl3" class="text-dark">شماره همراه</asp:Label>

            </td>
            <td style="align-content:center;text-align:right;">
                <asp:Label ID="Mobile" class="text-dark">@Model.Mobile</asp:Label>


            </td>

        </tr>*@
        <tr>
            <td style="width:50%; align-content:center;text-align:center;">
                <label id="lbl4" class="text-dark bg-info">میزان پرداخت</label>

            </td>
            <td style="width:50%;align-content:center;text-align:center;">
                <label id="Amount" class="text-dark bg-info">@Model.Amount</label>
            </td>

        </tr>
    </table>

    <table class="table" style="width:100%;align-content:center;">
        <tr>
            <td style="align-content:center;text-align:center;">
                <button id="back-btn" class="btn btn-success bg-info" onclick="backToKargozar()">بازگشت به سایت  نام ساز</button>
            </td>
        </tr>
    </table>

</div>


<script>
    var loc;    
    loc = '@PaymentData.SiteAddress';
    document.getElementById("back-btn").innerHTML='بازگشت به سایت';
    
    function backToKargozar()  {
        window.location = loc;
    }
</script>